# Generated by Django 5.2.3 on 2025-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=150, null=True)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
